@echo off
setlocal enabledelayedexpansion
chcp 65001 > nul
title VFX SOTA - Worker 설치

echo =====================================================
echo   VFX SOTA Monitor - Worker 설치
echo   (Gemma 4 26B LLM 스코어링 - GPU PC 용)
echo =====================================================
echo.
echo 이 컴퓨터에는 RTX 4090/5080/5090 같은 GPU가 필요합니다.
echo Gemma 4 26B 모델 용량: 약 17 GB
echo.
pause

REM Check Python
echo [확인] Python...
where python >nul 2>&1
if errorlevel 1 (
    echo [ERROR] Python 3.12+ 필요. https://python.org
    pause
    exit /b 1
)
python --version

REM Check Ollama
echo [확인] Ollama...
where ollama >nul 2>&1
if errorlevel 1 (
    echo.
    echo [ERROR] Ollama가 설치되어 있지 않습니다.
    echo         https://ollama.com/download 에서 설치 후 재실행
    pause
    exit /b 1
)
ollama --version

REM Check Gemma 4
echo.
echo [확인] gemma4:26b 모델...
ollama list | findstr /c:"gemma4:26b" >nul
if errorlevel 1 (
    echo.
    echo gemma4:26b 모델이 없습니다. 다운로드합니다 (약 17GB, 시간 걸림)...
    ollama pull gemma4:26b
    if errorlevel 1 (
        echo [ERROR] 모델 다운로드 실패
        pause
        exit /b 1
    )
)
echo OK.

set PROJECT_ROOT=%~dp0..
cd /d "%PROJECT_ROOT%\ai_cluster_worker"

echo.
echo [1/3] Worker 가상환경 생성...
if not exist .venv (
    python -m venv .venv
)

echo [2/3] Worker 의존성 설치...
call .venv\Scripts\activate.bat
python -m pip install --quiet --upgrade pip
python -m pip install --quiet openai httpx pyyaml tqdm
if errorlevel 1 (
    echo [ERROR] 의존성 설치 실패
    pause
    exit /b 1
)

echo.
echo [3/3] Worker 설정 (config.yaml)...
if exist config.yaml (
    echo config.yaml이 이미 있습니다. 재생성하려면 먼저 삭제하세요.
    goto :done
)

echo.
echo ---------------------------------------------------
echo Web Server 정보를 입력하세요.
echo ---------------------------------------------------
echo.
echo 예시:
echo   - 같은 PC:      http://127.0.0.1:8001
echo   - 같은 LAN:     http://192.168.1.100:8001
echo   - Tailscale:    http://100.101.102.103:8001
echo   - Cloudflare:   https://vfx-sota.yourdomain.com
echo.
set /p MAIN_PC_URL="Web Server URL: "
echo.
echo ADMIN_TOKEN은 Web Server의 .env 파일에 있는 값과 동일해야 합니다.
set /p ADMIN_TOKEN="ADMIN_TOKEN: "

(
    echo # Generated by install-worker.bat
    echo MAIN_PC_URL: !MAIN_PC_URL!
    echo ADMIN_TOKEN: !ADMIN_TOKEN!
    echo OLLAMA_BASE_URL: http://localhost:11434/v1
    echo OLLAMA_MODEL: gemma4:26b
    echo OLLAMA_TIMEOUT: 300
    echo BATCH_SIZE: 4
    echo MAX_ITEMS_PER_RUN: 50
    echo TEMPERATURE: 0.3
) > config.yaml
echo config.yaml 생성됨.

:done
echo.
echo =====================================================
echo   Worker 설치 완료
echo =====================================================
echo.
echo 실행 방법:
echo   - 1회 실행:    scripts\run-worker-once.bat
echo   - 주기 실행:   scripts\start-worker.bat
echo   - 자동 실행:   scripts\install-worker-schedule.bat  (Task Scheduler 등록)
echo.
pause
